# Root Cause Analysis

1. Aggregate transaction-level data.
To make the analysis more meaningful, I introduced controlled perturbations to simulate noticeable growth patterns.

2. Select a target merchant and benchmark key business metrics (e.g., transaction amount, transaction count) against peer merchants within the same category.

In [1]:
import pandas as pd
import numpy as np
import etl
from itertools import combinations

from config import DIMENSION_COLS

In [2]:
# Load transaction data


df_comparison = etl.load_data()

/Users/yanxinye/github/competency-intelligence/ci/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
df_comparison.head()

,generation,state,gender,category,merchant,amt_ly,amt_ty
0,Boomer,AL,F,entertainment,fraud_Abbott-Rogahn,4.110,82.600000
1,Boomer,AL,F,entertainment,fraud_Abshire PLC,206.715,29.081219
2,Boomer,AL,F,entertainment,fraud_Bauch-Blanda,0.000,0.000000
3,Boomer,AL,F,entertainment,fraud_Beier LLC,0.000,0.000000
4,Boomer,AL,F,entertainment,fraud_Bins-Tillman,77.965,983.120000

Given a target merchant, create a peer set under the same category, and compare the business metrics against it.

In [3]:
TARGET_MERCHANTS = "fraud_Kilback LLC" 

df_combined = etl.preprocess(df_comparison, TARGET_MERCHANTS)

Total amount in LY: 90116.45826107437
Total amount difference: 108492.6530555585
Total growth: 120.39%
Target industry of fraud_Kilback LLC: ['food_dining', 'grocery_pos']
Average growth of target: 120.39%
Average growth of peers: 94.52%
Average growth difference between target and peers: 25.87%

In [4]:
df_combined.head()

,generation,state,gender,category,merchant_target,amt_ly,amt_ty,amt_diff,amt_growth_ctc,amt_ty_peer,amt_ly_peer,amt_diff_peer,amt_growth_ctc_peer,merchant_peer,amt_growth_ctc_diff
0,Boomer,AL,F,food_dining,fraud_Kilback LLC,323.040000,776.92,453.880000,0.005037,294.358221,111.020952,183.337270,0.001763,ex-fraud_Kilback LLC,0.003273
1,Boomer,AL,F,grocery_pos,fraud_Kilback LLC,213.750000,0.00,-213.750000,-0.002372,385.485086,280.136657,105.348429,0.001013,ex-fraud_Kilback LLC,-0.003385
2,Boomer,AL,M,food_dining,fraud_Kilback LLC,191.370000,0.00,-191.370000,-0.002124,116.033160,101.086665,14.946496,0.000144,ex-fraud_Kilback LLC,-0.002267
3,Boomer,AL,M,grocery_pos,fraud_Kilback LLC,68.841556,974.84,905.998444,0.010054,341.726490,238.168357,103.558134,0.000996,ex-fraud_Kilback LLC,0.009058
4,Boomer,AR,F,food_dining,fraud_Kilback LLC,8.715000,0.00,-8.715000,-0.000097,129.949393,58.063871,71.885521,0.000691,ex-fraud_Kilback LLC,-0.000788

## Root Cause Analysis

In [5]:
df_combined.sort_values(by="amt_growth_ctc_diff", ascending=False).head()

,generation,state,gender,category,merchant_target,amt_ly,amt_ty,amt_diff,amt_growth_ctc,amt_ty_peer,amt_ly_peer,amt_diff_peer,amt_growth_ctc_peer,merchant_peer,amt_growth_ctc_diff
545,Millennial,TX,F,grocery_pos,fraud_Kilback LLC,1192.993940,8094.64,6901.646060,0.076586,3895.925881,1786.410407,2109.515474,0.020291,ex-fraud_Kilback LLC,0.056295
269,Gen X,NY,F,grocery_pos,fraud_Kilback LLC,173.480000,6040.20,5866.720000,0.065102,2157.218700,937.360481,1219.858219,0.011734,ex-fraud_Kilback LLC,0.053368
167,Gen X,CA,F,grocery_pos,fraud_Kilback LLC,888.458749,5724.92,4836.461251,0.053669,1583.183763,964.689093,618.494670,0.005949,ex-fraud_Kilback LLC,0.047720
531,Millennial,PA,F,grocery_pos,fraud_Kilback LLC,851.775000,4752.72,3900.945000,0.043288,1966.006811,934.293435,1031.713376,0.009924,ex-fraud_Kilback LLC,0.033364
439,Millennial,GA,M,grocery_pos,fraud_Kilback LLC,149.175000,3326.92,3177.745000,0.035263,387.123329,134.481102,252.642227,0.002430,ex-fraud_Kilback LLC,0.032833

In [6]:
target_col = "amt_growth_ctc_diff"

def grpby_dim_val(df, dim, target_col):
    kv = {}
    for i in df[[target_col, dim]].groupby(dim).sum().reset_index().to_dict("records"):

        k = "{} = {}".format(dim, i[dim])
        v = i[target_col]
        kv.update({k: v})
    return kv


res = {}
for dim in DIMENSION_COLS:
    res.update(grpby_dim_val(df_combined, dim, target_col))

res

{'generation = Boomer': -0.026154580370409283,
 'generation = Gen X': 0.1409785058528681,
 'generation = Gen Z': 0.04217049081909939,
 'generation = Millennial': 0.11142497033787593,
 'generation = Unknown': -0.009698757938148592,
 'state = AK': 0.0008035831663092299,
 'state = AL': 0.02110529744852842,
 'state = AR': 0.008043891042281457,
 'state = AZ': 0.02778962678680367,
 'state = CA': 0.07940780993199537,
 'state = CO': -0.005777093415928829,
 'state = CT': -0.006696088490714657,
 'state = DC': -0.0106194591967056,
 'state = DE': 0.0032924468429108944,
 'state = FL': 0.004663515186054068,
 'state = GA': 0.02719966835136314,
 'state = HI': 0.0019122430431895987,
 'state = IA': -0.00020631917465406893,
 'state = ID': -0.01002556609733837,
 'state = IL': 0.022018568496416552,
 'state = IN': 0.036191059476547556,
 'state = KS': -0.02688552851552631,
 'state = KY': 0.0033788604376908723,
 'state = LA': 0.007019722405038718,
 'state = MA': -0.0027200736183304085,
 'state = MD': 0.014564671575832695,
 'state = ME': -0.003471943098143702,
 'state = MI': -0.036818201943288414,
 'state = MN': 0.006902137428855926,
 'state = MO': -0.032859537115551306,
 'state = MS': -0.016401450814004518,
 'state = MT': 0.008407955821859499,
 'state = NC': 0.006630730916875136,
 'state = ND': 0.013638657587568784,
 'state = NE': 0.012866746637732664,
 'state = NH': -0.016054084553133667,
 'state = NJ': -0.017429446183959488,
 'state = NM': -0.008768003415638374,
 'state = NV': -0.0018381849758332238,
 'state = NY': 0.03453577467987707,
 'state = OH': -0.00865594267196225,
 'state = OK': 0.014924695894309418,
 'state = OR': 0.010613509849754784,
 'state = PA': 0.03312298944836029,
 'state = RI': -0.0016266937524830047,
 'state = SC': 0.03603518889617639,
 'state = SD': 0.003886598785679477,
 'state = TN': 0.014567973963641227,
 'state = TX': -0.022349960578224984,
 'state = UT': -0.004889005672047503,
 'state = VA': 0.014207654070674066,
 'state = VT': 0.007961046663260783,
 'state = WA': 0.019942116359658854,
 'state = WI': 0.005573582398254031,
 'state = WV': 0.013850337895860966,
 'state = WY': -0.02224544950460737,
 'gender = F': 0.18816128542160515,
 'gender = M': 0.07055934327968041,
 'category = food_dining': 0.1358071101396365,
 'category = grocery_pos': 0.12291351856164905}

In [9]:

target_col = "amt_growth_ctc_diff"

def grpby_dim_val(df, dims, target_col):
    kv = {}

    # make dims always a list
    if isinstance(dims, str):
        dims = [dims]

    grouped = (
        df[dims + [target_col]]
        .groupby(dims, dropna=False)[target_col]
        .sum()
        .reset_index()
    )

    for row in grouped.to_dict("records"):
        k_parts = [f"{dim} = {row[dim]}" for dim in dims]
        k = ", ".join(k_parts)
        v = row[target_col]
        kv[k] = v

    return kv


res = {}

# single dims
for dim in DIMENSION_COLS:
    res.update(grpby_dim_val(df_combined, dim, target_col))

# pairs of dims
for pair in combinations(DIMENSION_COLS, 2):
    res.update(grpby_dim_val(df_combined, list(pair), target_col))

In [10]:
res

{'generation = Boomer': -0.026154580370409283,
 'generation = Gen X': 0.1409785058528681,
 'generation = Gen Z': 0.04217049081909939,
 'generation = Millennial': 0.11142497033787593,
 'generation = Unknown': -0.009698757938148592,
 'state = AK': 0.0008035831663092299,
 'state = AL': 0.02110529744852842,
 'state = AR': 0.008043891042281457,
 'state = AZ': 0.02778962678680367,
 'state = CA': 0.07940780993199537,
 'state = CO': -0.005777093415928829,
 'state = CT': -0.006696088490714657,
 'state = DC': -0.0106194591967056,
 'state = DE': 0.0032924468429108944,
 'state = FL': 0.004663515186054068,
 'state = GA': 0.02719966835136314,
 'state = HI': 0.0019122430431895987,
 'state = IA': -0.00020631917465406893,
 'state = ID': -0.01002556609733837,
 'state = IL': 0.022018568496416552,
 'state = IN': 0.036191059476547556,
 'state = KS': -0.02688552851552631,
 'state = KY': 0.0033788604376908723,
 'state = LA': 0.007019722405038718,
 'state = MA': -0.0027200736183304085,
 'state = MD': 0.014564671575832695,
 'state = ME': -0.003471943098143702,
 'state = MI': -0.036818201943288414,
 'state = MN': 0.006902137428855926,
 'state = MO': -0.032859537115551306,
 'state = MS': -0.016401450814004518,
 'state = MT': 0.008407955821859499,
 'state = NC': 0.006630730916875136,
 'state = ND': 0.013638657587568784,
 'state = NE': 0.012866746637732664,
 'state = NH': -0.016054084553133667,
 'state = NJ': -0.017429446183959488,
 'state = NM': -0.008768003415638374,
 'state = NV': -0.0018381849758332238,
 'state = NY': 0.03453577467987707,
 'state = OH': -0.00865594267196225,
 'state = OK': 0.014924695894309418,
 'state = OR': 0.010613509849754784,
 'state = PA': 0.03312298944836029,
 'state = RI': -0.0016266937524830047,
 'state = SC': 0.03603518889617639,
 'state = SD': 0.003886598785679477,
 'state = TN': 0.014567973963641227,
 'state = TX': -0.022349960578224984,
 'state = UT': -0.004889005672047503,
 'state = VA': 0.014207654070674066,
 'state = VT': 0.007961046663260783,
 'state = WA': 0.019942116359658854,
 'state = WI': 0.005573582398254031,
 'state = WV': 0.013850337895860966,
 'state = WY': -0.02224544950460737,
 'gender = F': 0.18816128542160515,
 'gender = M': 0.07055934327968041,
 'category = food_dining': 0.1358071101396365,
 'category = grocery_pos': 0.12291351856164905,
 'generation = Boomer, state = AL': 0.006678002414190035,
 'generation = Boomer, state = AR': -0.0026558928894743344,
 'generation = Boomer, state = AZ': 0.0053272501642419225,
 'generation = Boomer, state = CA': -0.009628879945110854,
 'generation = Boomer, state = CO': -0.0021222604561960522,
 'generation = Boomer, state = CT': 0.0007491965008997788,
 'generation = Boomer, state = FL': 0.005489658780142479,
 'generation = Boomer, state = GA': -0.007871563040968933,
 'generation = Boomer, state = IA': -0.0096477343908032,
 'generation = Boomer, state = ID': -0.0038792971264812147,
 'generation = Boomer, state = IL': 0.02299892378338415,
 'generation = Boomer, state = IN': 0.01151499729075459,
 'generation = Boomer, state = KS': -0.00816273036658877,
 'generation = Boomer, state = KY': -0.00723657207895956,
 'generation = Boomer, state = LA': 0.01921185521628852,
 'generation = Boomer, state = MA': 0.008050295754138855,
 'generation = Boomer, state = MD': -0.005497658035613532,
 'generation = Boomer, state = ME': -0.007681430153231191,
 'generation = Boomer, state = MI': -0.013548257177399483,
 'generation = Boomer, state = MN': 0.016541610934092857,
 'generation = Boomer, state = MO': -0.010911612085835489,
 'generation = Boomer, state = MS': -0.00448501164206789,
 'generation = Boomer, state = MT': 0.005171206882051624,
 'generation = Boomer, state = NC': -0.005202488434135547,
 'generation = Boomer, state = ND': 0.008862726316381712,
 'generation = Boomer, state = NE': 0.01367261674588239,
 'generation = Boomer, state = NH': -0.006157949335152135,
 'generation = Boomer, state = NJ': -0.0022417701051033164,
 'generation = Boomer, state = NM': -0.004279388525722405,
 'generation = Boomer, state = NV': -0.0020501645963646414,
 'generation = Boomer, state = NY': -0.018110356005475017,
 'generation = Boomer, state = OH': -0.013468065927798723,
 'generation = Boomer, state = OK': 0.009613174074098367,
 'generation = Boomer, state = OR': 0.004996164739085374,
 'generation = Boomer, state = PA': 0.0033798105561129825,
 'generation = Boomer, state = SC': 0.021635205121287897,
 'generation = Boomer, state = SD': -0.003041449579228945,
 'generation = Boomer, state = TN': -0.0079974386488518,
 'generation = Boomer, state = TX': -0.01918123721406034,
 'generation = Boomer, state = UT': 0.0015761876179887265,
 'generation = Boomer, state = VA': -0.001886480287491575,
 'generation = Boomer, state = VT': 0.009784708126413294,
 'generation = Boomer, state = WA': -0.0022454679916311016,
 'generation = Boomer, state = WI': -0.017626071763415595,
 'generation = Boomer, state = WV': -0.004590943584683201,
 'generation = Gen X, state = AK': -0.0008375423227685664,
 'generation = Gen X, state = AL': -0.007379535007288114,
 'generation = Gen X, state = AR': 0.013615360927890473,
 'generation = Gen X, state = CA': 0.08390266793708054,
 'generation = Gen X, state = CO': -0.005649318663527345,
 'generation = Gen X, state = CT': -0.0024292907353150013,
 'generation = Gen X, state = DC': 0.0024836200284564696,
 'generation = Gen X, state = FL': -0.006916232224189345,
 'generation = Gen X, state = GA': 0.013948791112221757,
 'generation = Gen X, state = HI': 0.004075481529661291,
 'generation = Gen X, state = IA': 0.003985280471239212,
 'generation = Gen X, state = ID': -0.006146268970857155,
 'generation = Gen X, state = IL': 0.017689053399407333,
 'generation = Gen X, state = IN': -0.004187475561868708,
 'generation = Gen X, state = KS': -0.008344192904800582,
 'generation = Gen X, state = KY': 0.021530457725526236,
 'generation = Gen X, state = LA': -0.002144690076691468,
 'generation = Gen X, state = MA': -0.0033097810618839775,
 'generation = Gen X, state = MD': 0.0030433114784302567,
 'generation = Gen X, state = ME': 0.004418143610999734,
 'generation = Gen X, state = MI': -0.00011357714981607286,
 'generation = Gen X, state = MN': -0.025485635324942784,
 'generation = Gen X, state = MO': -0.015398192503968575,
 'generation = Gen X, state = MS': -0.00021633502943373584,
 'generation = Gen X, state = MT': 0.004811948417452214,
 'generation = Gen X, state = NC': 0.00036001072766514593,
 'generation = Gen X, state = ND': -0.001964780938131023,
 'generation = Gen X, state = NE': -0.006092802816330211,
 'generation = Gen X, state = NH': -0.0037493640626927445,
 'generation = Gen X, state = NJ': -0.006647905348488253,
 'generation = Gen X, state = NM': 0.006429827062568286,
 'generation = Gen X, state = NY': 0.07700858753362858,
 'generation = Gen X, state = OH': -0.012066819327915361,
 'generation = Gen X, state = OK': 0.019475096757392677,
 'generation = Gen X, state = OR': -0.003924733698869795,
 'generation = Gen X, state = PA': -0.004092470552753456,
 'generation = Gen X, state = SC': -0.002711562075582607,
 'generation = Gen X, state = SD': 0.007132278892494316,
 'generation = Gen X, state = TN': 0.015972856918120608,
 'generation = Gen X, state = TX': -0.027982260925982206,
 'generation = Gen X, state = UT': -0.00215378282067423,
 'generation = Gen X, state = VA': -0.005902356735741657,
 'generation = Gen X, state = VT': -0.0016537370503343337,
 'generation = Gen X, state = WA': 0.02705104046891257,
 'generation = Gen X, state = WI': 0.0021089934265246125,
 'generation = Gen X, state = WV': -0.009809554226378829,
 'generation = Gen X, state = WY': -0.010754104455578069,
 'generation = Gen Z, state = AL': -0.0008070673803488449,
 'generation = Gen Z, state = AR': -0.0002097859237830494,
 'generation = Gen Z, state = AZ': -0.0013585233306648808,
 'generation = Gen Z, state = CA': -0.0012650785546826754,
 'generation = Gen Z, state = DE': 0.0032924468429108944,
 'generation = Gen Z, state = GA': -0.0010892687651859472,
 'generation = Gen Z, state = IA': -0.003789682974753582,
 'generation = Gen Z, state = IL': -0.0001440102513438731,
 'generation = Gen Z, state = IN': 0.03095898376446322,
 'generation = Gen Z, state = KS': -0.009540392634223193,
 'generation = Gen Z, state = KY': 0.006162686803739118,
 'generation = Gen Z, state = ME': 0.004099719549739774,
 'generation = Gen Z, state = MN': 0.00042955382872840887,
 'generation = Gen Z, state = MO': -0.0010829788309925214,
 'generation = Gen Z, state = MS': -0.0018071644573116937,
 'generation = Gen Z, state = NC': 0.0025227732962403698,
 'generation = Gen Z, state = NH': -0.00030670414562260017,
 'generation = Gen Z, state = NM': 0.001346064177039483,
 'generation = Gen Z, state = NV': -0.0005045124161216081,
 'generation = Gen Z, state = NY': 0.00434570198339798,
 'generation = Gen Z, state = OH': -0.0007029582314777939,
 'generation = Gen Z, state = PA': 0.0037825732705749097,
 'generation = Gen Z, state = SC': 0.0063656335836088235,
 'generation = Gen Z, state = TN': 0.0027545590067030675,
 'generation = Gen Z, state = TX': -0.0054806890097154285,
 'generation = Gen Z, state = VA': -0.00019694566288150253,
 'generation = Gen Z, state = VT': 0.0011708299683177103,
 'generation = Gen Z, state = WA': 0.0026985987767028192,
 'generation = Gen Z, state = WI': 0.0005261285360420063,
 'generation = Millennial, state = AK': 0.0034076887871778865,
 'generation = Millennial, state = AL': 0.02538047310789884,
 'generation = Millennial, state = AR': -0.0013240247016366078,
 'generation = Millennial, state = AZ': 0.022658763599037304,
 'generation = Millennial, state = CA': 0.012134032436318616,
 'generation = Millennial, state = CO': 0.004468022170399905,
 'generation = Millennial, state = CT': -0.005015994256299434,
 'generation = Millennial, state = DC': -0.013103079225162068,
 'generation = Millennial, state = FL': 0.015958427985748612,
 'generation = Millennial, state = GA': 0.02819554332271646,
 'generation = Millennial, state = HI': -0.0021632384864716924,
 'generation = Millennial, state = IA': 0.010511069641451713,
 'generation = Millennial, state = IL': -0.017425670192291146,
 'generation = Millennial, state = IN': -0.013223412215591892,
 'generation = Millennial, state = KS': -0.0009343861451925747,
 'generation = Millennial, state = KY': -0.0056744489151639,
 'generation = Millennial, state = LA': -0.00446611233879198,
 'generation = Millennial, state = MA': -0.004143907117636804,
 'generation = Millennial, state = MD': 0.020410695040842603,
 'generation = Millennial, state = ME': -0.00208788528399663,
 'generation = Millennial, state = MI': -0.01884121817653425,
 'generation = Millennial, state = MN': -0.00806798102857412,
 'generation = Millennial, state = MO': -0.0004329636111347103,
 'generation = Millennial, state = MS': -0.009892939685191199,
 'generation = Millennial, state = MT': -0.001575199477644339,
 'generation = Millennial, state = NC': 0.004522220431381074,
 'generation = Millennial, state = ND': -0.010158337814853351,
 'generation = Millennial, state = NE': 0.010458531957781344,
 'generation = Millennial, state = NH': -0.00584006700966619,
 'generation = Millennial, state = NJ': -0.002370874079867547,
 'generation = Millennial, state = NM': -0.012264506129523739,
 'generation = Millennial, state = NV': 0.0007164920366530259,
 'generation = Millennial, state = NY': -0.019597441883164757,
 'generation = Millennial, state = OH': 0.011476094627358841,
 'generation = Millennial, state = OK': -0.011170061776232993,
 'generation = Millennial, state = OR': 0.004529269464087958,
 'generation = Millennial, state = PA': 0.01833042463517098,
 'generation = Millennial, state = RI': -0.0016266937524830047,
 'generation = Millennial, state = SC': 0.013584067950192203,
 'generation = Millennial, state = SD': -0.002716746077902513,
 'generation = Millennial, state = TN': 0.004427132274704685,
 'generation = Millennial, state = TX': 0.031857919383716654,
 'generation = Millennial, state = UT': -0.004311410469361999,
 'generation = Millennial, state = VA': 0.015356075133887002,
 'generation = Millennial, state = VT': -0.0013407543811358887,
 'generation = Millennial, state = WA': -0.004820046464994309,
 'generation = Millennial, state = WI': 0.01556386655549344,
 'generation = Millennial, state = WV': 0.031249312786459454,
 'generation = Millennial, state = WY': -0.009181752294103028,
 'generation = Unknown, state = AK': -0.0017665632981000903,
 'generation = Unknown, state = AL': -0.002766575685923489,
 'generation = Unknown, state = AR': -0.0013817663707150242,
 'generation = Unknown, state = AZ': 0.0011621363541893229,
 'generation = Unknown, state = CA': -0.005734931941610259,
 'generation = Unknown, state = CO': -0.002473536466605338,
 'generation = Unknown, state = FL': -0.009868339355647678,
 'generation = Unknown, state = GA': -0.005983834277420202,
 'generation = Unknown, state = IA': -0.00126525192178821,
 'generation = Unknown, state = IL': -0.0010997282427399149,
 'generation = Unknown, state = IN': 0.011127966198790345,
 'generation = Unknown, state = KS': 9.61735352788041e-05,
 'generation = Unknown, state = KY': -0.01140326309745102,
 'generation = Unknown, state = LA': -0.005581330395766359,
 'generation = Unknown, state = MA': -0.003316681192948482,
 'generation = Unknown, state = MD': -0.003391676907826631,
 'generation = Unknown, state = ME': -0.002220490821655388,
 'generation = Unknown, state = MI': -0.004315149439538604,
 'generation = Unknown, state = MN': 0.02348458901955157,
 'generation = Unknown, state = MO': -0.00503379008362001,
 'generation = Unknown, state = MS': 0.0,
 'generation = Unknown, state = NC': 0.004428214895724092,
 'generation = Unknown, state = ND': 0.016899050024171445,
 'generation = Unknown, state = NE': -0.0051715992496008615,
 'generation = Unknown, state = NJ': -0.006168896650500371,
 'generation = Unknown, state = NY': -0.009110716948509717,
 'generation = Unknown, state = OH': 0.006105806187870787,
 'generation = Unknown, state = OK': -0.0029935131609486344,
 'generation = Unknown, state = OR': 0.0050128093454512475,
 'generation = Unknown, state = PA': 0.011722651539254874,
 'generation = Unknown, state = SC': -0.002838155683329926,
 'generation = Unknown, state = SD': 0.0025125155503166186,
 'generation = Unknown, state = TN': -0.0005891355870353314,
 'generation = Unknown, state = TX': -0.0015636928121836669,
 'generation = Unknown, state = VA': 0.006837361622901798,
 'generation = Unknown, state = WA': -0.0027420084293311264,
 'generation = Unknown, state = WI': 0.005000665643609568,
 'generation = Unknown, state = WV': -0.0029984770795364575,
 'generation = Unknown, state = WY': -0.002309592754926273,
 'generation = Boomer, gender = F': -0.01223591092421969,
 'generation = Boomer, gender = M': -0.013918669446189592,
 'generation = Gen X, gender = F': 0.0787533973776162,
 'generation = Gen X, gender = M': 0.062225108475251895,
 'generation = Gen Z, gender = F': 0.050600519647136806,
 'generation = Gen Z, gender = M': -0.008430028828037416,
 'generation = Millennial, gender = F': 0.07911117160185858,
 'generation = Millennial, gender = M': 0.032313798736017356,
 'generation = Unknown, gender = F': -0.008067892280786767,
 'generation = Unknown, gender = M': -0.001630865657361828,
 'generation = Boomer, category = food_dining': 0.014592264744625518,
 'generation = Boomer, category = grocery_pos': -0.0407468451150348,
 'generation = Gen X, category = food_dining': 0.05392952440452028,
 'generation = Gen X, category = grocery_pos': 0.08704898144834781,
 'generation = Gen Z, category = food_dining': 0.02907792789150592,
 'generation = Gen Z, category = grocery_pos': 0.013092562927593468,
 'generation = Millennial, category = food_dining': 0.04540691787279894,
 'generation = Millennial, category = grocery_pos': 0.06601805246507698,
 'generation = Unknown, category = food_dining': -0.007199524773814163,
 'generation = Unknown, category = grocery_pos': -0.0024992331643344293,
 'state = AK, gender = M': 0.0008035831663092299,
 'state = AL, gender = F': 0.01910553216305301,
 'state = AL, gender = M': 0.0019997652854754164,
 'state = AR, gender = F': 0.002288363407856836,
 'state = AR, gender = M': 0.005755527634424621,
 'state = AZ, gender = F': 0.024931763384279118,
 'state = AZ, gender = M': 0.002857863402524546,
 'state = CA, gender = F': 0.043169305953383606,
 'state = CA, gender = M': 0.03623850397861176,
 'state = CO, gender = F': -0.013290888386371434,
 'state = CO, gender = M': 0.007513794970442604,
 'state = CT, gender = F': -0.011483232316652844,
 'state = CT, gender = M': 0.004787143825938187,
 'state = DC, gender = F': -0.012456394330233737,
 'state = DC, gender = M': 0.001836935133528138,
 'state = DE, gender = F': 0.0032924468429108944,
 'state = FL, gender = F': 0.007143746355073444,
 'state = FL, gender = M': -0.002480231169019376,
 'state = GA, gender = F': -0.01229613204337677,
 'state = GA, gender = M': 0.039495800394739905,
 'state = HI, gender = F': -0.0021632384864716924,
 'state = HI, gender = M': 0.004075481529661291,
 'state = IA, gender = F': -0.002709814806932484,
 'state = IA, gender = M': 0.002503495632278416,
 'state = ID, gender = F': -0.00474130106320146,
 'state = ID, gender = M': -0.00528426503413691,
 'state = IL, gender = F': 0.011117474727817508,
 'state = IL, gender = M': 0.010901093768599044,
 'state = IN, gender = F': 0.0285942753140732,
 'state = IN, gender = M': 0.007596784162474355,
 'state = KS, gender = F': -0.02171716400465201,
 'state = KS, gender = M': -0.005168364510874305,
 'state = KY, gender = F': 0.013795455532012122,
 'state = KY, gender = M': -0.01041659509432125,
 'state = LA, gender = F': 0.017893937446877603,
 'state = LA, gender = M': -0.010874215041838886,
 'state = MA, gender = F': -0.01317049454782493,
 'state = MA, gender = M': 0.01045042092949452,
 'state = MD, gender = F': -0.005239162366423026,
 'state = MD, gender = M': 0.01980383394225572,
 'state = ME, gender = F': 0.004105391147996849,
 'state = ME, gender = M': -0.0075773342461405505,
 'state = MI, gender = F': -0.014822089789744737,
 'state = MI, gender = M': -0.021996112153543673,
 'state = MN, gender = F': -0.007660931481263458,
 'state = MN, gender = M': 0.014563068910119385,
 'state = MO, gender = F': -0.02506776188747737,
 'state = MO, gender = M': -0.0077917752280739355,
 'state = MS, gender = F': -0.01698471826363131,
 'state = MS, gender = M': 0.0005832674496267939,
 'state = MT, gender = F': 0.0009469698429569397,
 'state = MT, gender = M': 0.0074609859789025595,
 'state = NC, gender = F': -0.0024095953148825355,
 'state = NC, gender = M': 0.009040326231757672,
 'state = ND, gender = F': 0.02009150696374626,
 'state = ND, gender = M': -0.006452849376177476,
 'state = NE, gender = F': 0.013667482312607839,
 'state = NE, gender = M': -0.000800735674875176,
 'state = NH, gender = F': -0.005515899157639335,
 'state = NH, gender = M': -0.010538185395494334,
 'state = NJ, gender = F': -0.016518485237017756,
 'state = NJ, gender = M': -0.00091096094694173,
 'state = NM, gender = F': 0.0060977063035494924,
 'state = NM, gender = M': -0.014865709719187867,
 'state = NV, gender = M': -0.0018381849758332238,
 'state = NY, gender = F': 0.015204221848881923,
 'state = NY, gender = M': 0.019331552830995146,
 'state = OH, gender = F': 0.007346857167238374,
 'state = OH, gender = M': -0.016002799839200624,
 'state = OK, gender = F': 0.012270572648284694,
 'state = OK, gender = M': 0.0026541232460247245,
 'state = OR, gender = F': 0.0009243653509892684,
 'state = OR, gender = M': 0.009689144498765515,
 'state = PA, gender = F': 0.05959025263801775,
 'state = PA, gender = M': -0.02646726318965746,
 'state = RI, gender = F': -0.0016266937524830047,
 'state = SC, gender = F': 0.03838697582351949,
 'state = SC, gender = M': -0.0023517869273431023,
 'state = SD, gender = F': 0.008310302605222709,
 'state = SD, gender = M': -0.004423703819543233,